# Generated by Django 2.2.4 on 2023-01-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('mobile_num', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('photograph', models.FileField(blank=True, default='', max_length=250, null=True, upload_to='identity_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_level', models.ManyToManyField(default='employee', related_name='members', to='group_project.userLevel')),
            ],
        ),
    ]
