# Generated by Django 2.2.4 on 2023-01-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='photograph',
            new_name='identity_image',
        ),
    ]
